name: 'Deploy Teams tab'
author: 'pl4nty'
description: 'Deploy a custom tab to Microsoft Teams'
branding:
    icon: 'upload-cloud'
    color: 'purple'
inputs:
  TENANT_ID:
    description: 'Azure AD tenant (directory) ID'
    required: true
  APP_ID:
    description: 'Azure AD application ID'
    required: true
  APP_SECRET:
    description: 'Azure AD application secret'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'